### ISSUE TITLE
Jedi crashed with FStringStart

### ISSUE THREAD

**Issue by hungrybirder** [deoplete-plugins/deoplete-jedi#223] opened 2019-03-28 07:56 UTC
# Problem summary
Jedi auto completion crashed

## Environment Information

 * OS: macOS Mojave 10.14.4
 * Neovim version: v0.3.4

Python 3.6.5,
pynvim 0.3.2

$ nvim test.py

```

class Student:
    def __init__(self, first_name, last_name):
        self.first_name = first_name
        self.last_name = last_name
        """here"""
        self.

    @property
    def full_name(self):
        fn = f'{self.first_name} {self.last_name}'
        return fn

```
When I type "self." jedi crashed with error message.

```

  File "/Users/liyong/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/liyong/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/__init__.py", line 200, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/liyong/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/__init__.py", line 212, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/liyong/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/liyong/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/__init__.py", line 216, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/liyong/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/liyong/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/liyong/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/syntax_tree.py", line 146, in eval_node
    return eval_or_test(context, element)
  File "/Users/liyong/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/syntax_tree.py", line 338, in eval_or_test
    iterator = iter(or_test.children)
AttributeError: 'FStringStart' object has no attribute 'children'
Error from jedi: 'FStringStart' object has no attribute 'children'.  Use :messages / see above for error details.

```

**Comment by airhuman** [comment] 2019-03-28 08:02
If I do not use f-string in full_name method. 
`
@property
    def full_name(self):
        fn = '{} {}'.format(self.first_name, self.last_name)
        return fn
`
then, everything is ok~

**Comment by danilo-augusto** [comment] 2019-05-21 19:20
Any progress on this? I'm having this error even without directly using f-strings (it's maybe because of an imported lib)...

The strange thing is, when I deactivate `deoplete-jedi` and instead activate `jedi` completion (another package), it works well.

So I wonder if it's not a matter of a frozen version of `jedi` or `parso` in the `vendored` folder, which maybe does not include the latest fixes.

By the way, is this repository maintained?
This issue was not addressed in the last 2 months.

Thank you

**Comment by blueyed** [comment] 2019-05-21 20:04
> So I wonder if it's not a matter of a frozen version of `jedi` or `parso` in the `vendored` folder, which maybe does not include the latest fixes.

I guess you could start investigating from there.. :)
Compare the versions and use git-bisect.

> By the way, is this repository maintained?

I am only using jedi-vim (mostly) myself.

**Comment by blueyed** [comment] 2019-05-21 20:14
https://github.com/deoplete-plugins/deoplete-jedi/pull/226 might fix it.

**Comment by blueyed** [comment] 2019-05-21 23:14
https://github.com/deoplete-plugins/deoplete-jedi/pull/226 was merged, please test it.
If it is still broken, please try updating jedi, but IIRC this was the latest release already, and master has a lot of new stuff.

**Comment by hungrybirder** [comment] 2019-05-22 02:51
> #226 was merged, please test it.
> If it is still broken, please try updating jedi, but IIRC this was the latest release already, and master has a lot of new stuff.

I upgraded deoplete-jedi, then it crashed again
`
(dev)  liyong@mbp  ~  cd .config/nvim/plugged/deoplete-jedi
(dev)  liyong@mbp  ~/.config/nvim/plugged/deoplete-jedi   master  git log -1 --oneline
55471c2 (grafted, HEAD -> master, origin/master, origin/HEAD) Merge pull request #226 from blueyed/update-parso
(dev)  liyong@mbp  ~/.config/nvim/plugged/deoplete-jedi   master  git submodule status
 0bf8a69024aff8599bd1f323c4feba2703ef3d59 rplugin/python3/deoplete/vendored/jedi (v0.13.3)
 8a06f0da0592b33ff002bf699d05e7c31a613b17 rplugin/python3/deoplete/vendored/parso (v0.4.0)
`

**Comment by blueyed** [comment] 2019-05-22 03:18
Try updating jedi then maybe.
It looks like jedi-vim has parso 0.3.4 (https://github.com/davidhalter/jedi-vim/tree/master/pythonx).

**Comment by blueyed** [comment] 2019-05-22 03:20
Otherwise please report this for jedi / parso.
FWIW FStringStart appears to come from parso, but the crash appears to be jedi only?!

**Comment by hungrybirder** [comment] 2019-05-22 03:26
> jedi / parso

From nvim :messages output only shows jedi Exception (AttributeError)

**Comment by hungrybirder** [comment] 2019-05-22 03:28
https://github.com/davidhalter/jedi/issues/1331

**Comment by blueyed** [comment] 2019-05-29 03:54
Could not reproduce it.
Is this the full traceback?

Please post the debug log from using a minimal vimrc `nvim -u minimal.vimrc`, from the deoplete-jedi dir:
```vim
set runtimepath+=../deoplete.nvim
set runtimepath+=.
let g:deoplete#sources#jedi#debug_server = 1
call deoplete#enable()
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

**Comment by blueyed** [comment] 2019-05-29 04:08
Unfortunately deoplete appears to not work at all anymore (using the minimal config), after updating it:
```
2019-05-29 06:04:19,182 INFO     [22434] (deoplete.logging) --- Deoplete Log Start ---
2019-05-29 06:04:19,183 INFO     [22434] (deoplete.logging) NVIM v0.4.0-816-g62d5137c8, Python 3.7.3, pynvim 0.3.2
2019-05-29 06:04:24,123 DEBUG    [22434] (deoplete.core) initialized context: {'changedtick': 4, 'event': 'Init', 'filetype': 'python', 'filetypes': ['python'], 'input': '', 'max_abbr_width': 61.333333333333336, 'max_kind_width': 61.333333333333336, 'max_info_width': 61.333333333333336, 'max_menu_width': 61.333333333333336, 'next_input': '', 'position': [0, 1, 1, 0], 'same_filetypes': [], 'bufnr': 1, 'bufname': 't-2.py', 'bufpath': '…/vim/plugged/deoplete-jedi/t-2.py', 'camelcase': False, 'complete_str': '', 'custom': {'filter': {}, 'source': {'_': {}}, 'option': {'camel_case': False, 'on_text_changed_i': True, 'max_list': 500, 'candidate_marks': [], 'skip_multibyte': False, 'auto_refresh_delay': 20, 'auto_complete_delay': 0, 'min_pattern_length': 2, 'yarp': False, 'profile': False, 'omni_patterns': {}, 'auto_complete': True, 'smart_case': 0, 'ignore_case': 0, 'sources': {}, 'refresh_always': True, 'num_processes': 4, 'keyword_patterns': {'_': '[a-zA-Z_]\\k*'}, 'on_insert_enter': True, 'trigger_key': '', 'skip_chars': ['(', ')'], 'prev_completion_mode': 'filter', 'ignore_sources': {}}}, 'cwd': '…/vim/plugged/deoplete-jedi', 'encoding': 'utf-8', 'ignorecase': 0, 'is_windows': 0, 'smartcase': 0, 'vars': {'deoplete#sources#jedi#debug_server': 1, 'deoplete#enable_at_startup': 1}, 'keyword_pattern': '[a-zA-Z_][\\w@0-9_À-ÿ]*', 'sources': [], 'rpc': 'deoplete_on_event'}
2019-05-29 06:04:24,123 DEBUG    [22434] (deoplete.core) on_event: Init
2019-05-29 06:04:24,125 DEBUG    [22434] (deoplete.core) Process 0: …/vim/plugged/deoplete-jedi/../deoplete.nvim/rplugin/python3/deoplete/source/omni.py
2019-05-29 06:04:24,136 DEBUG    [22434] (deoplete.core) Process 1: …/vim/plugged/deoplete-jedi/../deoplete.nvim/rplugin/python3/deoplete/source/buffer.py
2019-05-29 06:04:24,151 DEBUG    [22434] (deoplete.core) Process 2: …/vim/plugged/deoplete-jedi/../deoplete.nvim/rplugin/python3/deoplete/source/file.py
2019-05-29 06:04:24,193 DEBUG    [22434] (deoplete.core) Process 3: …/vim/plugged/deoplete-jedi/../deoplete.nvim/rplugin/python3/deoplete/source/around.py
2019-05-29 06:04:24,195 DEBUG    [22434] (deoplete.core) Process 0: …/vim/plugged/deoplete-jedi/../deoplete.nvim/rplugin/python3/deoplete/source/member.py
2019-05-29 06:04:24,197 DEBUG    [22434] (deoplete.core) Process 1: …/vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py
2019-05-29 06:04:24,229 DEBUG    [22434] (deoplete.core) initialized context: {'changedtick': 4, 'event': 'InsertEnter', 'filetype': 'python', 'filetypes': ['python'], 'input': '', 'max_abbr_width': 61.333333333333336, 'max_kind_width': 61.333333333333336, 'max_info_width': 61.333333333333336, 'max_menu_width': 61.333333333333336, 'next_input': '', 'position': [0, 1, 1, 0], 'same_filetypes': [], 'bufnr': 1, 'bufname': 't-2.py', 'bufpath': '…/vim/plugged/deoplete-jedi/t-2.py', 'camelcase': False, 'complete_str': '', 'custom': {'filter': {}, 'source': {'_': {}}, 'option': {'camel_case': False, 'on_text_changed_i': True, 'max_list': 500, 'candidate_marks': [], 'skip_multibyte': False, 'auto_refresh_delay': 20, 'auto_complete_delay': 0, 'min_pattern_length': 2, 'yarp': False, 'profile': False, 'omni_patterns': {}, 'auto_complete': True, 'smart_case': 0, 'ignore_case': 0, 'sources': {}, 'refresh_always': True, 'num_processes': 4, 'keyword_patterns': {'_': '[a-zA-Z_]\\k*'}, 'on_insert_enter': True, 'trigger_key': '', 'skip_chars': ['(', ')'], 'prev_completion_mode': 'filter', 'ignore_sources': {}}}, 'cwd': '…/vim/plugged/deoplete-jedi', 'encoding': 'utf-8', 'ignorecase': 0, 'is_windows': 0, 'smartcase': 0, 'vars': {'deoplete#sources#jedi#debug_server': 1, 'deoplete#enable_at_startup': 1}, 'keyword_pattern': '[a-zA-Z_][\\w@0-9_À-ÿ]*', 'sources': [], 'rpc': 'deoplete_on_event'}
2019-05-29 06:04:24,229 DEBUG    [22434] (deoplete.core) on_event: InsertEnter
2019-05-29 06:04:42,410 DEBUG    [22434] (deoplete.core) completion_begin (TextChangedI): 'c'
2019-05-29 06:04:42,413 DEBUG    [22434] (deoplete.core) do_complete (TextChangedI): 0 candidates, input=c, complete_position=-1, is_async=1
2019-05-29 06:04:43,678 DEBUG    [22434] (deoplete.core) completion_begin (TextChangedI): 'cl'
2019-05-29 06:04:43,682 DEBUG    [22434] (deoplete.core) do_complete (TextChangedI): 0 candidates, input=cl, complete_position=-1, is_async=1
2019-05-29 06:04:44,410 DEBUG    [22434] (deoplete.core) completion_begin (TextChangedI): 'cla'
2019-05-29 06:04:44,412 DEBUG    [22434] (deoplete.core) do_complete (TextChangedI): 0 candidates, input=cla, complete_position=-1, is_async=1
2019-05-29 06:04:45,211 DEBUG    [22434] (deoplete.core) completion_begin (TextChangedI): 'clas'
2019-05-29 06:04:45,213 DEBUG    [22434] (deoplete.core) do_complete (TextChangedI): 0 candidates, input=clas, complete_position=-1, is_async=1
2019-05-29 06:04:45,891 DEBUG    [22434] (deoplete.core) completion_begin (TextChangedI): 'class'
2019-05-29 06:04:45,895 DEBUG    [22434] (deoplete.core) do_complete (TextChangedI): 0 candidates, input=class, complete_position=-1, is_async=1
2019-05-29 06:04:49,038 DEBUG    [22434] (deoplete.core) completion_begin (TextChangedI): 'clas'
2019-05-29 06:04:49,040 DEBUG    [22434] (deoplete.core) do_complete (TextChangedI): 0 candidates, input=clas, complete_position=-1, is_async=1
2019-05-29 06:04:49,822 DEBUG    [22434] (deoplete.core) completion_begin (TextChangedI): 'cla'
2019-05-29 06:04:49,826 DEBUG    [22434] (deoplete.core) do_complete (TextChangedI): 0 candidates, input=cla, complete_position=-1, is_async=1
```
I.e. it does not even complete from the buffer source anymore.
(but it works with my real config still, where I only load it on demand)

**Comment by Shougo** [comment] 2019-05-29 04:15
@blueyed Please create new issue in deoplete.  I will test it.

**Comment by blueyed** [comment] 2019-05-29 04:27
@Shougo 
Thanks, it is unrelated to this issue here.  Created https://github.com/Shougo/deoplete.nvim/issues/979.

**Comment by Shougo** [comment] 2019-05-29 04:30
I will check it later

**Comment by hungrybirder** [comment] 2019-06-03 09:40
Close it.

**Closed** 2019-06-03 09:40 UTC
Labels: bug
